### ISSUE TITLE
Unable to verify the access token

### ISSUE THREAD

**Issue by Dominantez** [3cixty/appchallenge#1]
I am trying to use the GoFlowIntegrationAPI in order to obtain a developer account but constantly receive the 400 error. I have a valid token that is properly recognised by the server (receive the same one in the answer). Do I need to present some other info except the access-key?

**Comment by pgraverdy** [comment]
Hi, we ran into the same issue and fixed a few issues. First just to make sure, Did you  installed the updated android 3cixty auth app (v0.4) ?

Also, did you use the goflow-integration branch for the android-client-sample or just the master branch ?

Animesh, should we merge into master ?

**Comment by congkinh** [comment]
In fact, when you got an appkey from [AppChallenge](http://appchallenge.3cixty.com/appkey/), your appkey was already integrated with Goflow backend. For developping crowdscourcing applications, you just need to use 3cixty access token to retrieve Goflow user accounts based on their Google accounts. Then, you are able to communicate with Goflow backend using the Goflow user accounts.

We have developed a [sample](https://github.com/3cixty/android-client-sample) to show how to get 3cixty access token from an appkey and how to get Goflow user account from a 3cixty access token. Moreover, we also showed how to call Goflow APIs using Goflow user accounts in the [`integrate-goflow-3` branch](https://github.com/3cixty/android-client-sample/tree/integrate-goflow-3). Please have a look at this repository as we just fixed a bug. If you have any problems, please let us know so that we could help you.

Note that you are required to install [3cixty OAuth client](https://play.google.com/store/apps/details?id=com.threecixty.auth&hl=en).

**Comment by Dominantez** [comment]
So we basically cannot obtain a valid token just using the website capabilities? I am developing for iOS, so it will take a while until I find an Android device...

**Comment by Dominantez** [comment]
The last question is still topical: is there a way to obtain a valid token for developers working with platforms other than Android?

**Comment by congkinh** [comment]
For now, we support two kinds of getting a 3cixty access token:
-  Web-based applications, please have a look at [our sample](https://github.com/3cixty/web-client-sample)
-  Android applications

**Comment by pgraverdy** [comment]
One important point regarding iOS

While it may be possible to use the Web URLs to retrieve the 3Cixty access token (although I don't know how complex this would be to implement), and later use the 3Cixty API, the crowdsourcing part of 3Cixty is also using some low-level communication protocols and the client library is only available for now on Android.

There is no plan to have an iOS version in the short term (it is planned but not for the near future, maybe early 2015).

**Comment by Dominantez** [comment]
Thank you very much for your replies.
